import { supabase } from './supabase'

/**
 * Referral System Helper Functions
 * 
 * Contains all referral-related database operations
 */

/**
 * Get user's referral data
 */
export const getUserReferralData = async (userId) => {
  try {
    const { data, error } = await supabase
      .from('users')
      .select('*')
      .eq('id', userId)
      .single()

    if (error) throw error
    return { data, error: null }
  } catch (error) {
    console.error('Error fetching user referral data:', error)
    return { data: null, error }
  }
}

/**
 * Validate referral code and get recruiter info
 */
export const validateReferralCode = async (referralCode) => {
  try {
    const { data, error } = await supabase
      .from('users')
      .select('id, referral_code, role')
      .eq('referral_code', referralCode)
      .single()

    if (error) throw error
    return { data, error: null }
  } catch (error) {
    console.error('Error validating referral code:', error)
    return { data: null, error }
  }
}

/**
 * Get referral tree for a user using recursive query
 */
export const getReferralTree = async (userId) => {
  try {
    const { data, error } = await supabase
      .rpc('get_referral_tree', { recruiter_id: userId })

    if (error) throw error
    return { data, error: null }
  } catch (error) {
    console.error('Error fetching referral tree:', error)
    return { data: null, error }
  }
}

/**
 * Get count of direct recruits
 */
export const getDirectRecruitsCount = async (userId) => {
  try {
    const { data, error } = await supabase
      .rpc('get_direct_recruits_count', { recruiter_id: userId })

    if (error) throw error
    return { data, error: null }
  } catch (error) {
    console.error('Error getting direct recruits count:', error)
    return { data: null, error }
  }
}

/**
 * Get count of all recruits in tree
 */
export const getTotalRecruitsCount = async (userId) => {
  try {
    const { data, error } = await supabase
      .rpc('get_total_recruits_count', { recruiter_id: userId })

    if (error) throw error
    return { data, error: null }
  } catch (error) {
    console.error('Error getting total recruits count:', error)
    return { data: null, error }
  }
}

/**
 * Create user with referral info (called during signup)
 */
export const createUserWithReferral = async (userId, email, parentId = null) => {
  try {
    const role = parentId ? 'recruited' : 'recruiter'

    const { data, error } = await supabase
      .from('users')
      .insert({
        id: userId,
        role: role,
        parent_id: parentId,
        // referral_code auto-generated by trigger
      })
      .select()
      .single()

    if (error) throw error
    return { data, error: null }
  } catch (error) {
    console.error('Error creating user with referral:', error)
    return { data: null, error }
  }
}

/**
 * Get head recruiter (top of the chain)
 */
export const getHeadRecruiter = async (userId) => {
  try {
    const { data, error } = await supabase
      .rpc('get_head_recruiter', { user_id: userId })

    if (error) throw error
    return { data, error: null }
  } catch (error) {
    console.error('Error getting head recruiter:', error)
    return { data: null, error }
  }
}

/**
 * Promote user to recruiter role
 */
export const promoteToRecruiter = async (userId) => {
  try {
    const { data, error } = await supabase
      .from('users')
      .update({ role: 'recruiter' })
      .eq('id', userId)
      .select()
      .single()

    if (error) throw error
    return { data, error: null }
  } catch (error) {
    console.error('Error promoting user to recruiter:', error)
    return { data: null, error }
  }
}

/**
 * Get user's parent (recruiter) info
 */
export const getParentRecruiter = async (userId) => {
  try {
    const { data: userData, error: userError } = await supabase
      .from('users')
      .select('parent_id')
      .eq('id', userId)
      .single()

    if (userError || !userData?.parent_id) {
      return { data: null, error: userError }
    }

    const { data: parentData, error: parentError } = await supabase
      .from('users')
      .select('*')
      .eq('id', userData.parent_id)
      .single()

    if (parentError) throw parentError
    return { data: parentData, error: null }
  } catch (error) {
    console.error('Error getting parent recruiter:', error)
    return { data: null, error }
  }
}

/**
 * Get all direct children (recruits) of a user
 */
export const getDirectRecruits = async (userId) => {
  try {
    const { data, error } = await supabase
      .from('users')
      .select('*')
      .eq('parent_id', userId)
      .order('created_at', { ascending: false })

    if (error) throw error
    return { data, error: null }
  } catch (error) {
    console.error('Error getting direct recruits:', error)
    return { data: null, error }
  }
}

/**
 * Build hierarchical tree structure from flat array
 */
export const buildTreeStructure = (flatData, parentId = null) => {
  return flatData
    .filter(node => node.parent_id === parentId)
    .map(node => ({
      ...node,
      children: buildTreeStructure(flatData, node.id)
    }))
}

/**
 * Generate shareable referral link
 */
export const generateReferralLink = (referralCode) => {
  const baseUrl = window.location.origin
  return `${baseUrl}/join/${referralCode}`
}

/**
 * Store referrer info in localStorage (used when visiting referral link)
 */
export const storeReferrerInfo = (referrerId, referralCode) => {
  localStorage.setItem('referrer_id', referrerId)
  localStorage.setItem('referral_code', referralCode)
}

/**
 * Get referrer info from localStorage
 */
export const getReferrerInfo = () => {
  return {
    referrerId: localStorage.getItem('referrer_id'),
    referralCode: localStorage.getItem('referral_code')
  }
}

/**
 * Clear referrer info from localStorage (after signup)
 */
export const clearReferrerInfo = () => {
  localStorage.removeItem('referrer_id')
  localStorage.removeItem('referral_code')
}

/**
 * Check if user is an admin
 */
export const isAdmin = async (userId) => {
  try {
    console.log('🔍 isAdmin checking userId:', userId)
    const { data, error } = await supabase
      .from('users')
      .select('role')
      .eq('id', userId)
      .single()

    console.log('📊 isAdmin query result:', { data, error })
    if (error) throw error
    const result = data?.role === 'admin'
    console.log('✅ isAdmin returning:', result, 'role:', data?.role)
    return result
  } catch (error) {
    console.error('❌ Error checking admin status:', error)
    return false
  }
}

/**
 * Get leaderboard of top recruiters by total recruits
 */
export const getRecruiterLeaderboard = async (limit = 10) => {
  try {
    // Get all users
    const { data: users, error } = await supabase
      .from('users')
      .select('*')

    if (error) throw error

    // Calculate recruit counts for each user
    const leaderboard = await Promise.all(
      users.map(async (user) => {
        const { data: count } = await getTotalRecruitsCount(user.id)
        return {
          ...user,
          total_recruits: count || 0
        }
      })
    )

    // Sort by total recruits and limit
    const sorted = leaderboard
      .sort((a, b) => b.total_recruits - a.total_recruits)
      .slice(0, limit)

    return { data: sorted, error: null }
  } catch (error) {
    console.error('Error getting recruiter leaderboard:', error)
    return { data: null, error }
  }
}
