-- =====================================================
-- FIX AUTH USER TO USERS TABLE SYNC
-- =====================================================
-- This creates a trigger that automatically adds users
-- to the users table when they sign up via auth
-- =====================================================

-- Drop existing trigger if any
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

-- Create or replace the handler function
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
SECURITY DEFINER
SET search_path = public
LANGUAGE plpgsql
AS $$
BEGIN
  -- Insert into users table when a new auth user is created
  -- Default role is 'recruiter', parent_id will be set by signup logic
  INSERT INTO public.users (id, role, parent_id, referral_code)
  VALUES (
    NEW.id, 
    'recruiter', 
    NULL,
    NULL  -- Will be auto-generated by trigger_auto_referral_code
  )
  ON CONFLICT (id) DO NOTHING;
  
  RETURN NEW;
END;
$$;

-- Create trigger on auth.users table
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

-- =====================================================
-- VERIFICATION
-- =====================================================
-- Check if trigger was created:
-- SELECT trigger_name, event_object_table, action_statement
-- FROM information_schema.triggers
-- WHERE trigger_name = 'on_auth_user_created';
